#!/bin/bash

usage() {
  cat <<EOM
Usage: $(basename "$0") <discoveryUrl> <clientId>

This script configures AgentCore Runtime based on the configuration

Parameters:
  <discoveryUrl>    : Discovery URL as generated by AWS Cognito setup
  <clientId>        : Client ID as generated by AWS Cognito setup
EOM
  exit 1 # Exit with a non-zero status to indicate failure (unless it's just a help request)
}

# Validate Arguments
if [ -z "$1" ]; then
  echo "ERROR: Missing mandatory parameter discoveryUrl." >&2 # Print error message to standard error
  usage
fi
if [ -z "$2" ]; then
  echo "ERROR: Missing mandatory parameter clientId." >&2 # Print error message to standard error
  usage
fi

# Configure AgentCore
uv sync
source .venv/bin/activate
uv pip freeze --exclude-editable > requirements.txt
agentcore configure --region us-east-1 --entrypoint src/emergingtechnologyresearch/agentCoreHandler.py --name emergingtechnologyresearch --requirements-file requirements.txt --protocol HTTP --verbose --non-interactive --authorizer-config '{"customJWTAuthorizer": {"discoveryUrl": "${1}","allowedClients": ["${2}"]}}'