#!/bin/bash
usage() {
  cat <<EOM
Usage: $(basename "$0") <clientId> <researchTopic>

This script invokes AgentCore Runtime

Parameters:
  <clientId>        : Client ID as generated by AWS Cognito setup
  <researchTopic>   : Topic to research on
EOM
  exit 1 # Exit with a non-zero status to indicate failure (unless it's just a help request)
}

# Validate Arguments
if [ -z "$1" ]; then
  echo "ERROR: Missing mandatory parameter clientId." >&2 # Print error message to standard error
  usage
fi
if [ -z "$2" ]; then
  echo "ERROR: Missing mandatory parameter researchTopic." >&2 # Print error message to standard error
  usage
fi

export TOKEN=$(aws cognito-idp initiate-auth \
            --client-id "$1" \
            --auth-flow USER_PASSWORD_AUTH \
            --auth-parameters USERNAME='agenticLearner',PASSWORD='helloAgentic' \
            --region us-east-1 | jq -r '.AuthenticationResult.AccessToken')
PAYLOAD='{"topic": "'${2}'"}'
COMMAND="agentcore invoke '"
COMMAND+=${PAYLOAD}
COMMAND+="' --bearer-token '"
COMMAND+=${TOKEN}
COMMAND+="'"

eval $COMMAND
